#!/bin/sh
set -x

wmakeLnInclude tetMetrics
wmakeLnInclude multiThreader
wmakeLnInclude springMotionSolver
wmakeLnInclude dynamicTopoFvMesh

wmake libso tetMetrics
wmake libso multiThreader
wmake libso springMotionSolver
wmake libso dynamicTopoFvMesh
