#!/bin/sh
set -x

# Clean out existing object files
wclean tetMetrics
wclean multiThreader
wclean springMotionSolver
wclean mesquiteSmoother
wclean fluidInterface
wclean edgeDiscretization
wclean dynamicTopoFvMesh
wclean interfaceTrackFoam

# Wipe out all lnInclude directories and re-link
wcleanLnIncludeAll

