#!/bin/sh
set -x

wmakeLnInclude coupleMap
wmakeLnInclude freeSurface
wmakeLnInclude enginePointPatchFields
wmakeLnInclude mesquiteMotionSolver
wmakeLnInclude dynamicTopoFvMesh
wmakeLnInclude interTrackFoam
