#!/bin/sh
set -x

./AllwmakeLnInclude

wmake libso tetMetrics
wmake libso multiThreader
wmake libso coupleMap
wmake libso fluidInterface
wmake libso mesquiteSmoother
wmake libso springMotionSolver
wmake libso dynamicTopoFvMesh
wmake interfaceTrackFoam
