#!/bin/sh
set -x

# Clean out existing object files
wclean mesquiteMotionSolver
wclean customPointPatchFields
wclean dynamicTopoFvMesh

(cd fluxCorrector; ./Allwclean)

# Wipe out all lnInclude directories and re-link
wcleanLnIncludeAll

