#!/bin/sh
set -x

wmakeLnInclude tetMetrics
wmakeLnInclude multiThreader
wmakeLnInclude coupleMap
wmakeLnInclude freeSurface
wmakeLnInclude mesquiteSmoother
wmakeLnInclude dynamicTopoFvMesh
wmakeLnInclude interfaceTrackFoam
